name: Daily postcode check

on:
  schedule:
    # Runs daily at 07:10 UTC (08:10 BST typically)
    - cron: "10 7 * * *"
  workflow_dispatch: {}

jobs:
  run-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.47.0
          playwright install --with-deps chromium
      - name: Run postcode check
        env:
          POSTCODE: GL51 8LS
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python check_postcode.py
